spring.application.name=NotificationServ
server.port=8000

# PostgreSQL Database configuration
# Explicação: Se houver a variável DATABASE_URL (da nuvem), o Spring usa. Se não houver, ele usa o seu localhost:5433 padrão para rodar na sua máquina.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


# SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# Credenciais GMAIL
app.mail.gmail.host=smtp.gmail.com
app.mail.gmail.username=notificationhubservice@gmail.com
app.mail.gmail.password=rdgtashsijvdcxpj

# Credenciais OUTLOOK
app.mail.outlook.host=smtp.outlook.com
app.mail.outlook.username=notif.hub@outlook.com
app.mail.outlook.password=wkvxlvepqyazldpn

# Kafka Configuração para Nuvem e Local
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notification-group-v2

# Configurações de Segurança do Kafka (Exigidas pelo Upstash na nuvem, ignoradas no localhost)
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:PLAIN}
spring.kafka.properties.sasl.jaas.config=${KAFKA_JAAS_CONFIG:}

spring.kafka.admin.fail-fast=false
spring.kafka.listener.missing-topics-fatal=false

app.firebase.config-path=${FIREBASE_CONFIG_PATH:src/main/resources/firebase-service-account.json}